name: Upload SARIF to GitHub Security

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  upload-sarif:
    name: Upload SARIF
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'C:\\Report\\cx_result.sarif'
